### ISSUE TITLE
Nhận đơn

### ISSUE THREAD

**Issue by PhucDang02** [oni2302/Delivery#11]

**Comment by PhucDang02** [comment]
*Giao diện:
- Layout chung: xem mô tả ở task "Xây dựng giao diện chung (website)" - Sprint 1
- Layout content:
   + Form: title "Nhận đơn". 
   + Hiển thị label và các khung input chứa thông tin tương ứng (readonly) (3 col - 4 row): mã đơn hàng, trạng thái, ghi chú, người gửi, số điện thoại người gửi, địa chỉ người gửi, người nhận, số điện thoại người nhận, số nhà, phường, quận, thành phố.
   + Button "Hủy", button "Nhận đơn"
*Xử lý:
- Load dữ liệu từ database hiển thị thông tin đơn hàng 
- Click button "Hủy" quay lại trang đơn hàng chờ xử lý
- Click button "Nhận đơn" cập nhật trạng thái đơn hàng thành "Đã nhận", sau đó quay lại trang đơn hàng chờ xử lý. Đơn hàng đã nhận sẽ được chuyển sang danh sách đơn đã nhận và xóa đơn đó ở danh sách đơn hàng chờ xử lý
*Lưu trữ: lưu thời gian nhận đơn và nhân viên nhận đơn

**Comment by DQKhair** [comment]
đã nhận

**Comment by DQKhair** [comment]
đã xong
