### ISSUE TITLE
Xây dựng giao diện mobile

### ISSUE THREAD

**Issue by PhucDang02** [oni2302/Delivery#14]
*Giao diện: 
- Layout chung: 
   + Header: hiển thị tiêu đề
   + Footer: hiển thị 4 button: trang chủ, thông tin đơn, quét mã QR, cá nhân
- Layout content: hiển thị giao diện tương ứng chức năng được chọn
*Xử lý: không
*Lưu trữ: không

**Comment by gods-oni** [comment]
Đã nhận

**Comment by gods-oni** [comment]
Đã xong nhớ
