### ISSUE TITLE
Xem danh sách tài khoản

### ISSUE THREAD

**Issue by PhucDang02** [oni2302/Delivery#15]

**Comment by PhucDang02** [comment]
*Giao diện:
- Layout chung: xem mô tả ở task "Xây dựng giao diện chung (website)" - Sprint 1
- Layout content:
   + Form tìm kiếm: 3 khung input - tên tài khoản, họ tên, loại tài khoản; button "Thêm tài khoản", button "Reset", button "Search"
   + Table (4 col): tên tài khoản, họ tên, loại tài khoản, action (icon switch, icon information)
*Xử lý:
- Load dữ liệu từ database hiển thị danh sách tài khoản
- Click button "Thêm tài khoản" chuyển sang trang thêm tài khoản
- Click button "Reset" xóa kết quả tìm kiếm, load lại trang
- Click button "Search" tìm kiếm thông tin tài khoản
- Click icon switch hiển thị form xác nhận reset mật khẩu
- Click icon information chuyển sang trang thông tin chi tiết của tài khoản
*Lưu trữ: không

**Comment by giangduc06** [comment]
Đã nhận

**Comment by giangduc06** [comment]
Đã xong

**Comment by giangduc06** [comment]
Đã nhận

**Comment by giangduc06** [comment]
Đã xong
