### ISSUE TITLE
Xem thông tin chi tiết đơn hàng

### ISSUE THREAD

**Issue by PhucDang02** [oni2302/Delivery#16]

**Comment by PhucDang02** [comment]
*Giao diện:
- Layout chung: xem mô tả ở task "Xây dựng giao diện chung (website)" - Sprint 1
- Layout content:
   + Form: title "Thông tin đơn hàng" 
   + Button "Quay lại"
   + Hiển thị label và các khung input chứa thông tin tương ứng (readonly) (3 col - 4 row): mã đơn hàng, trạng thái, ghi chú, người gửi, số điện thoại người gửi, địa chỉ người gửi, người nhận, số điện thoại người nhận, số nhà, phường, quận, thành phố.
*Xử lý:
- Load dữ liệu từ database hiển thị thông tin đơn hàng 
- Click "Quay lại" quay lại trang đơn hàng chờ xử lý
*Lưu trữ: không

**Comment by DQKhair** [comment]
đã nhận

**Comment by DQKhair** [comment]
đã xong
