### ISSUE TITLE
Thêm tài khoản

### ISSUE THREAD

**Issue by PhucDang02** [oni2302/Delivery#20]

**Comment by PhucDang02** [comment]
*Giao diện:
- Layout chung: xem mô tả ở task "Xây dựng giao diện chung (website)" - Sprint 1
- Layout content:
   + Form: title "Thêm tài khoản"
   + Hiển thị label và khung input (2 col - 2 row): Role, tên nhân viên (nhân viên chưa có tài khoản), username, password
   + Button "Thêm", button "Hủy"
*Xử lý:
- Load dữ liệu database hiển thị tên của nhân viên chưa có tài khoản
- Click button "Thêm" sẽ lưu thông tin tài khoản đã thêm và hiển thị ở danh sách tài khoản
- Click button "Hủy" quay về trang danh sách tài khoản
*Lưu trữ: thông tin tài khoản (role, username, password)

**Comment by giangduc06** [comment]
Đã nhận

**Comment by giangduc06** [comment]
Đã xong
