### ISSUE TITLE
Xem danh sách đơn hàng đã nhận

### ISSUE THREAD

**Issue by PhucDang02** [oni2302/Delivery#21]

**Comment by PhucDang02** [comment]
*Giao diện:
- Layout chung: xem mô tả ở task "Xây dựng giao diện chung (website)" - Sprint 1
- Layout content:
   + Title "Đơn hàng đã nhận"
   + Khung tìm kiếm, button tìm kiếm
   + Table (5 col): mã đơn hàng, nhân viên nhận, thời gian nhận, trạng thái, actions
   + Button "Chi tiết", button "Phân phối"
*Xử lý:
- Load dữ liệu từ database hiển thị thông tin đơn hàng 
- Click button "Chi tiết" chuyển sang trang chi tiết đơn hàng
- Click button "Phân phối" chuyển sang trang phân phối đơn hàng
*Lưu trữ: không

**Comment by DQKhair** [comment]
đã nhận

**Comment by DQKhair** [comment]
đã xong

**Comment by PhucDang02** [comment]
Fix: 
*Giao diện:
  - Trong danh sách đơn đa nhận, thêm 1 button "Phân phối"
*Xử lý: 
  - Click button "Phân phối" chuyển sang trang phân phối đơn hàng cho shipper

**Comment by DQKhair** [comment]
đã nhận

**Comment by DQKhair** [comment]
đã xong
