### ISSUE TITLE
Xem danh sách đơn hàng (mobile)

### ISSUE THREAD

**Issue by PhucDang02** [oni2302/Delivery#24]

**Comment by PhucDang02** [comment]
*Giao diện: 
- Layout chung: 
   + Header: hiển thị tiêu đề
   + Footer: hiển thị 4 button: trang chủ, thông tin đơn, quét mã QR, cá nhân
- Layout content: Hiển thị danh sách đơn hàng: mã đơn, tên người nhận, địa chỉ, số điện thoại, trạng thái đơn hàng
*Xử lý: load dữ liệu từ database hiển thị thông tin đơn hàng (mã đơn, tên người nhận, địa chỉ, số điện thoại, trạng thái)
*Lưu trữ: không

**Comment by gods-oni** [comment]
Đã nhận

**Comment by gods-oni** [comment]
Xong
