### ISSUE TITLE
Reset mật khẩu

### ISSUE THREAD

**Issue by PhucDang02** [oni2302/Delivery#27]
*Giao diện:
   - Form: title "Reset", text "Bạn có chắc reset mật khẩu cho tài khoản này?"  
   - Hiển thị tên tài khoản được chọn
   - Button "Reset", button "Cancel"
*Xử lý:
- Load dữ liệu từ database hiển thị tên tài khoản tương ứng
- Click button "Reset" sẽ cập nhật lại mật khẩu mặc định cho tài khoản là "User@GHK2P", hiển thị thông báo sau khi reset mật khẩu
- Click button "Cancal" quay lại trang danh sách tài khoản
*Lưu trữ: lưu mật khẩu mới nếu chọn reset

**Comment by giangduc06** [comment]
Đã nhận

**Comment by giangduc06** [comment]
Đã xong
