### ISSUE TITLE
Nhận đơn được giao (mobile)

### ISSUE THREAD

**Issue by PhucDang02** [oni2302/Delivery#30]
*Giao diện: 
- Layout chung: 
   + Header: hiển thị tiêu đề
   + Footer: hiển thị 4 button: trang chủ, thông tin đơn, quét mã QR, cá nhân
- Layout content: Hiển thị danh sách đơn hàng: mã đơn, tên người nhận, địa chỉ, số điện thoại, trạng thái đơn hàng
*Xử lý: sau khi shipper đăng nhập sẽ chuyển đến trang danh sách đơn hàng và chuyển trạng thái đơn hàng thành "Shipper đã nhận đơn". Load dữ liệu từ database hiển thị thông tin đơn hàng (mã đơn, tên người nhận, địa chỉ, số điện thoại, trạng thái)
*Lưu trữ: trạng thái đơn hàng

**Comment by gods-oni** [comment]
Đã nhận

**Comment by gods-oni** [comment]
Đã xong
