### ISSUE TITLE
Xem danh sách đơn hàng đã phân phối

### ISSUE THREAD

**Issue by PhucDang02** [oni2302/Delivery#31]

**Comment by PhucDang02** [comment]
*Giao diện:
- Layout chung: xem mô tả ở task "Xây dựng giao diện chung (website)" - Sprint 1
- Layout content:
   + Title "Danh sách đơn hàng"
   + Khung tìm kiếm, button tìm kiếm
   + Table (7 col): mã đơn hàng, người gửi, địa chỉ người gửi, người nhận, địa chỉ người nhận, trạng thái, actions
   + Button "Chi tiết"
*Xử lý:
- Load dữ liệu từ database hiển thị thông tin đơn hàng 
- Click button "Chi tiết" chuyển sang trang theo dõi trạng thái đơn hàng
*Lưu trữ: không

**Comment by DQKhair** [comment]
đã nhận

**Comment by DQKhair** [comment]
đã xong
