### ISSUE TITLE
Quét mã QR cập nhật trạng thái đơn hàng (mobile)

### ISSUE THREAD

**Issue by PhucDang02** [oni2302/Delivery#32]
*Giao diện: 
- Layout content: 
   + Vùng camera quét mã
   + Button trạng thái (hiển thị lần lượt sau khi được nhấn: đã lấy hàng, đang giao hàng, đã giao hàng)
 *Xử lý: 
- Quét QK lấy mã đơn hàng: sau khi quét hiển thị mã đơn
- Nhấn button cập nhật trạng thái tương ứng 
   + Sau khi quét hiển thị button "Đã lấy hàng"
   + Sau khi nhấn button "Đã lấy hàng" hiển thị button "Đang giao hàng". Trạng thái được cập nhật thành đã lấy hàng
   + Sau khi nhấn button "Đang giao hàng" hiển thị button "Đã giao hàng"  Trạng thái được cập nhật thành đang giao hàng
   + Nhấn button "Đã giao hàng" cập nhật trạng thái thành đã giao hàng
*Lưu trữ: lưu trạng thái được cập nhật và thời gian cập nhật

**Comment by PhucDang02** [comment]
*Giao diện:
- Text view: Xác nhận nhận đơn
- Button "Xác nhận", button "Hủy"
*Xử lý: click vào button Xác nhận sẽ cập nhật trạng thái đơn hàng, click button Hủy sẽ trở lại trang Chi tiết đơn hàng
*Lưu trữ: trạng thái đơn hàng và mã đơn hàng

**Comment by gods-oni** [comment]
Đã nhận

**Comment by gods-oni** [comment]
Xong

**Comment by gods-oni** [comment]
Xong
