### ISSUE TITLE
Theo dõi trạng thái đơn hàng (mobile)

### ISSUE THREAD

**Issue by PhucDang02** [oni2302/Delivery#37]
*Giao diện: 
- Layout chung: 
   + Header: hiển thị tiêu đề "Chi tiết đơn hàng"
   + Footer: hiển thị 4 button: trang chủ, thông tin đơn, quét mã QR, cá nhân
- Layout content: 
  //Phần thông tin đơn hàng:
   + Khung thông tin đơn hàng: mã đơn hàng, trạng thái đơn hàng
   + Khung thông tin người gửi: tên người gửi, địa chỉ, số điện thoại
   + Khung thông tin người nhận: tên người gửi, địa chỉ, số điện thoại
   + Khung ghi chú: thông tin được ghi chú
  //Phần button cập nhật trạng thái:
   + Button "Đã lấy hàng"
   + Buton "Đang giao hàng"
   + Button "Đã giao hàng"
  //Phần trạng thái đơn hàng
   +Tiêu đề: "Trạng thái"
   + Timeline trạng thái đơn hàng: tên trạng thái và thời gian cập nhật trạng thái
*Xử lý: 
- Load dữ liệu từ database hiển thị thông tin đơn hàng (mã đơn, tên người nhận, địa chỉ người nhận, số điện thoại người nhận,  tên người gửi, địa chỉ người gửi, số điện thoại người gửi, trạng thái)
- Trạng thái đơn hàng thay đổi sau mỗi khi được cập nhật 
*Lưu trữ: không

**Comment by gods-oni** [comment]
Đã nhận

**Comment by gods-oni** [comment]
Xong
