### ISSUE TITLE
Xây dựng giao diện chung (WEB)

### ISSUE THREAD

**Issue by PhucDang02** [oni2302/Delivery#4]

**Comment by PhucDang02** [comment]
*Giao diện:
-Layout chung:
   + Header: navigation-bar: tên người dùng, ảnh đại diện, icon mũi tên (dropdown - profile, settings, help, log out)
   + Sidebar (shadow, left):
        > Logo
        > Quản lý tài khoản
        > Quản lý nhân viên
        > Nhận đơn
        > Phân phối đơn
        > Theo dõi đơn
        > Báo cáo thống kê
   + Footer: text: © 2023 GHK2P
- Layout content (right): hiển thị các trang với chức năng tương ứng
*Xử lý: load dữ liệu từ database hiển thị chức năng
*Lưu trữ: không

**Comment by gods-oni** [comment]
Đã nhận

**Comment by gods-oni** [comment]
Đã xong
