### ISSUE TITLE
Theo dõi trạng thái đơn hàng

### ISSUE THREAD

**Issue by PhucDang02** [oni2302/Delivery#40]
*Giao diện:
- Layout chung: xem mô tả ở task "Xây dựng giao diện chung (website)" - Sprint 1
- Layout content:
   + Title: Trạng thái đơn hàng có mã x (x là mã đơn hàng)
   + Thông tin người gửi, người nhận và địa chỉ giao hàng
   + Mốc thời gian và trạng thái của đơn hàng (có tất cả 7 trạng thái: chờ xử lý, đã nhận, đã phân phối, shipper đã nhận đơn, đã lấy hàng, đang giao hàng, đã giao hàng) 
*Xử lý:
- Load dữ liệu từ database hiển thị mã đơn hàng, thông tin người gửi, người nhận và địa chỉ giao hàng 
- Load dữ liệu từ database hiển thị thời gian và trạng thái của đơn hàng
*Lưu trữ: không

**Comment by DQKhair** [comment]
ĐÃ NHẬN

**Comment by DQKhair** [comment]
đã xong
