### ISSUE TITLE
Xem danh sách nhân viên

### ISSUE THREAD

**Issue by DQKhair** [oni2302/Delivery#44]
*Giao diện:
- Layout chung: xem mô tả ở task "Xây dựng giao diện chung (website)" - Sprint 1
- Layout content:
   + Form tìm kiếm: 3 khung input - mã nhân viên, họ tên, khu vực hoạt động; button "Thêm tài khoản", button "Reset", button "Search"
   + Table (7 col): mã nhân viên, họ tên, ngày sinh, email, số điện thoại, khu vực hoạt động, action - button "Xóa"
*Xử lý:
- Load dữ liệu từ database hiển thị danh sách nhân viên 
- Click button "Thêm nhân viên" chuyển sang trang thêm nhân viên
- Click button "Reset" xóa kết quả tìm kiếm, load lại trang
- Click button "Search" tìm kiếm thông tin nhân viên
- Click button "Xóa" chuyển sang trang xác nhận xóa
*Lưu trữ: thông tin tài khoản

**Comment by PhucDang02** [comment]
Đã nhận

**Comment by PhucDang02** [comment]
Đã xong
