### ISSUE TITLE
Thêm, xóa nhân viên

### ISSUE THREAD

**Issue by DQKhair** [oni2302/Delivery#46]
THÊM NHÂN VIÊN
*Giao diện:
- Layout chung: xem mô tả ở task "Xây dựng giao diện chung (website)" - Sprint 1
- Layout content:
   + Form: title "Thêm nhân viên"
   + Hiển thị label và khung input (3 col - 2 row): họ tên, ngày sinh, email, số điện thoại, khu vực hoạt động
   + Button "Thêm", button "Hủy"
*Xử lý:
- Load dữ liệu từ database hiển thị tên các khu vực 
- Click button "Thêm" sẽ lưu thông tin nhân viên đã thêm, hiển thị thông báo thêm thành công và hiển thị nhân viên đã thêm ở danh sách nhân viên
- Click button "Hủy" quay về trang danh sách nhân viên
*Lưu trữ: thông tin nhân viên (họ tên, ngày sinh, email, số điện thoại, khu vực hoạt động)
--------------------------------------------------------------------------------------
XÓA NHÂN VIÊN
*Giao diện:
- Layout chung: xem mô tả ở task "Xây dựng giao diện chung (website)" - Sprint 1
- Layout content:
   + Form: title "Xác nhận xóa nhân viên?"
   + Hiển thị label và thông tin nhân viên tương ứng: mã nhân viên, họ tên, ngày sinh, email, số điện thoại
   + Button "Xóa", button "Hủy"
*Xử lý:
- Load dữ liệu từ database hiển thị thông tin nhân viên tương ứng
- Click button "Hủy" hiển thị thông báo xóa thành công và xóa nhân viên khỏi danh sách nhân viên 
- Click button "Hủy" quay về trang danh sách nhân viên
*Lưu trữ: Trạng thái của nhân viên chuyển từ 1 (đang hoạt động) thành 0 (đã nghỉ)

**Comment by PhucDang02** [comment]
Đã nhận

**Comment by PhucDang02** [comment]
Đã xong
