### ISSUE TITLE
Cập nhật thông tin cá nhân

### ISSUE THREAD

**Issue by DQKhair** [oni2302/Delivery#47]
*Giao diện:
- Layout chung: xem mô tả ở task "Xây dựng giao diện chung (website)" - Sprint 1
- Layout content:
   + Form: title "Thông tin cá nhân". 
   + Hiển thị label và các khung input (3 col - 3 row) mã nhân viên (disabled), role (disabled), tên tài khoản (disabled), khu vực hoạt động (disabled), họ tên, ngày sinh, email, số điện thoại, ảnh đại diện.
   + Button "Đổi mật khẩu", button "Lưu"
*Xử lý:
- Load dữ liệu từ database hiển thị thông tin cá nhân 
- Click button "Đổi mật khẩu" chuyển sang trang đổi mật khẩu
- Click button "Lưu" cập nhập lại thông tin cá nhân mới nếu có thay đổi
*Lưu trữ: thông tin cá nhân mới

**Comment by hiepbao** [comment]
Đã nhận

**Comment by hiepbao** [comment]
Đã xong
