### ISSUE TITLE
Tìm kiếm thông tin nhân viên

### ISSUE THREAD

**Issue by DQKhair** [oni2302/Delivery#48]
*Giao diện:
- Layout chung: xem mô tả ở task "Xây dựng giao diện chung (website)" - Sprint 1
- Layout content:
   + Form tìm kiếm: 3 khung input - mã nhân viên, họ tên, khu vực hoạt động; button "Thêm tài khoản", button "Reset", button "Search"
   + Table (7 col): mã nhân viên, họ tên, ngày sinh, email, số điện thoại, khu vực hoạt động, action - button "Xóa"
*Xử lý:
- Sau khi nhập từ khóa tìm kiếm và nhấn button "search", hiển thị nhân viên tương ứng với từ khóa đã tìm kiếm
*Lưu trữ: không

**Comment by PhucDang02** [comment]
Đã nhận

**Comment by PhucDang02** [comment]
Đã xong
