### ISSUE TITLE
Đổi mật khẩu

### ISSUE THREAD

**Issue by DQKhair** [oni2302/Delivery#49]
*Giao diện:
- Layout chung: xem mô tả ở task "Xây dựng giao diện chung (website)" - Sprint 1
- Layout content:
   + Form: title "Đổi mật khẩu"
   + Label và khung input: tên tài khoản (readonly), mật khẩu cũ, mật khẩu mới, nhập lại mật khẩu.
   + Check box hiển thị mật khẩu
   + Button "Lưu"
*Xử lý:
- Click button "Lưu" sẽ kiểm tra mật khẩu có đúng yêu cầu không, nếu đúng lưu mật khẩu mới, nếu sai yêu cầu nhập lại. Hiển thị thông báo sau khi đổi mật khẩu thành công.
- Mật khẩu được mã hóa và yêu cầu ràng buộc (có ký tự in hoa, ký tự thường, ký tự đặc biệt và số).
*Lưu trữ: mật khẩu mới

**Comment by hiepbao** [comment]
Đã nhận

**Comment by hiepbao** [comment]
Đã xong
