### ISSUE TITLE
Tìm kiếm thông tin tài khoản

### ISSUE THREAD

**Issue by DQKhair** [oni2302/Delivery#50]
*Giao diện:
- Layout chung: xem mô tả ở task "Xây dựng giao diện chung (website)" - Sprint 1
- Layout content:
   + Form tìm kiếm: 3 khung input - tên tài khoản, họ tên, loại tài khoản; button "Thêm tài khoản", button "Reset", button "Search"
   + Table (4 col): tên tài khoản, họ tên, loại tài khoản, action (icon switch, icon information)
*Xử lý:
- Sau khi nhập từ khóa tìm kiếm và nhấn button "search", hiển thị tài khoản tương ứng với từ khóa đã tìm kiếm
*Lưu trữ: không

**Comment by PhucDang02** [comment]
Đã nhận

**Comment by PhucDang02** [comment]
Đã xong
