### ISSUE TITLE
Xem thống kê đơn đã giao

### ISSUE THREAD

**Issue by DQKhair** [oni2302/Delivery#53]
*Giao diện:
- Layout chung: xem mô tả ở task "Xây dựng giao diện chung (website) - Sprint 1"
- Layout content: 
   + Title: Biểu đồ thống kê đơn đã giao
   + 2 Form-select: chọn năm và tháng để thống kê
   + Biểu đồ: 
      > Kiểu Barchart
      > Primary horizontal "Số lượng", primary vertical "Thời gian (ngày)"
      > Legend top "Số lượng đơn đã giao"
*Xử lý: Sau khi chọn thời gian thống kê (năm và tháng), load dữ liệu từ database hiển thị số lượng đơn đã giao tương ứng với thời gian đã chọn.
*Lưu trữ: không

**Comment by PhucDang02** [comment]
Đã nhận

**Comment by PhucDang02** [comment]
Đã nhận

**Comment by PhucDang02** [comment]
Đã nhận

**Comment by PhucDang02** [comment]
Đã xong
