### ISSUE TITLE
Xác nhận đang giao hàng (mobile)

### ISSUE THREAD

**Issue by DQKhair** [oni2302/Delivery#55]
*Giao diện: 
- Layout chung: 
   + Header: hiển thị tiêu đề "Chi tiết đơn hàng"
   + Footer: hiển thị 4 button: trang chủ, thông tin đơn, quét mã QR, cá nhân
- Layout content: 
  //Phần thông tin đơn hàng:
   + Khung thông tin đơn hàng: mã đơn hàng, trạng thái đơn hàng
   + Khung thông tin người gửi: tên người gửi, địa chỉ, số điện thoại
   + Khung thông tin người nhận: tên người gửi, địa chỉ, số điện thoại
   + Khung ghi chú: thông tin được ghi chú
  //Phần button cập nhật trạng thái:
   + Button "Đã lấy hàng"
   + Buton "Đang giao hàng"
   + Button "Đã giao hàng"
  //Phần trạng thái đơn hàng
   +Tiêu đề: "Trạng thái"
   + Timeline trạng thái đơn hàng: tên trạng thái và thời gian cập nhật trạng thái
*Xử lý: 
- Load dữ liệu từ database hiển thị thông tin đơn hàng (mã đơn, tên người nhận, địa chỉ người nhận, số điện thoại người nhận,  tên người gửi, địa chỉ người gửi, số điện thoại người gửi, trạng thái)
- Click button "Đang giao hàng" sẽ cập nhật trạng thái của đơn sang "Đang giao hàng"
*Lưu trữ: lưu trạng thái được cập nhật và thời gian cập nhật

**Comment by hiepbao** [comment]
đã nhận

**Comment by hiepbao** [comment]
đã xong
