### ISSUE TITLE
Đăng xuất

### ISSUE THREAD

**Issue by PhucDang02** [oni2302/Delivery#6]

**Comment by PhucDang02** [comment]
*Giao diện:
- Sử dụng giao diện chung
- Trên header, drop down ở icon mũi tên: list-item "Log out"
*Xử lý: click "Log out" trở về trang Log in và xóa session
*Lưu trữ: không

**Comment by giangduc06** [comment]
Đã nhận

**Comment by giangduc06** [comment]
Đã xong
