### ISSUE TITLE
Phân phối đơn hàng

### ISSUE THREAD

**Issue by PhucDang02** [oni2302/Delivery#64]
*Giao diện:
- Layout chung: xem mô tả ở task "Xây dựng giao diện chung (website)" - Sprint 1
- Layout content:
   + Form: title "Phân phối đơn hàng" 
   + Hiển thị label và các khung input chứa thông tin tương ứng (readonly) (3 col - 4 row): mã đơn hàng, trạng thái, ghi chú, người gửi, số điện thoại người gửi, địa chỉ người gửi, người nhận, số điện thoại người nhận, số nhà, phường, quận, thành phố.
   + Label phân phối: form-select hiển thị tên nhân viên giao hàng 
   + Button "Phân phối", button "Hủy"
*Xử lý:
- Load dữ liệu từ database hiển thị thông tin đơn hàng
- Load dữ liệu từ database hiển thị tên nhân viên giao hàng tương ứng với quận trong địa chỉ người nhận
- Click "Phân phối" cập nhật trạng thái đơn hàng sang đã phân phối. Sau đó quay lại trang đơn hàng đã nhận. Đơn hàng phân phối sẽ được chuyển sang danh sách đơn và xóa đơn đó ở danh sách đơn hàng đã nhận.
- Click "Hủy" quay lại trang đơn hàng đã nhận
*Lưu trữ: không

**Comment by DQKhair** [comment]
đã nhận

**Comment by DQKhair** [comment]
đã xong
