### ISSUE TITLE
Xem thông tin chi tiết tài khoản

### ISSUE THREAD

**Issue by DQKhair** [oni2302/Delivery#65]
*Giao diện:
- Layout chung: xem mô tả ở task "Xây dựng giao diện chung (website)" - Sprint 1
- Layout content:
   + Form: title "Thông tin tài khoản" 
   + Hiển thị label và các khung input (readonly) (3 col - 3 row): mã nhân viên, role, tên tài khoản, họ tên, ngày sinh, email, số điện thoại, khu vực hoạt động
   + Button "Hủy"
*Xử lý:
- Load dữ liệu từ database hiển thị thông tin tài khoản
- Click button "Hủy" quay về trang danh sách tài khoản
*Lưu trữ: không

**Comment by PhucDang02** [comment]
Đã nhận

**Comment by PhucDang02** [comment]
Done
