### ISSUE TITLE
Xem danh sách đơn hàng chờ xử lý

### ISSUE THREAD

**Issue by PhucDang02** [oni2302/Delivery#8]

**Comment by PhucDang02** [comment]
*Giao diện:
- Layout chung: xem mô tả ở task "Xây dựng giao diện chung (website)" - Sprint 1
- Layout content:
   + Title "Đơn hàng chờ xử lý"
   + Khung tìm kiếm, button tìm kiếm
   + Table (7 col): mã đơn hàng, người gửi, địa chỉ người gửi, người nhận, địa chỉ người nhận, trạng thái, actions
   + Button "Chi tiết", button "Nhận đơn"
*Xử lý:
- Load dữ liệu từ database hiển thị thông tin đơn hàng 
- Click button "Chi tiết" chuyển sang trang chi tiết đơn hàng
- Click button "Nhận đơn" chuyển sang trang nhận đơn
*Lưu trữ: không

**Comment by DQKhair** [comment]
đã nhận

**Comment by DQKhair** [comment]
đã xong
